version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5433:5432"
    networks:
      - pg-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    networks:
      - pg-network
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do
          echo 'Waiting for postgress...'; sleep 1;
        done;
        php setup.php && php-fpm
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

networks:
  pg-network:

volumes:
  pg-data:
